language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: qWM4/dyZArClaWp1TKjSb/xDwMbKIm+JVw4s1Q9w53DhCgm2QS4tJs1ZHZsdfri8j3tDuXQhA2iBgToShQzAsa04DsFlpn7uMExzzddVNy8VfwP5VvxeVrR3WEa71/wJxbWgEsxLFf8V9E+CYHjuG7zA/AAx1MHFi4Y9G8nEkRAjyIGbANfmCf9/4uR1zxOu3LcJspkf2BvsvT9Jhqww5INc28eWXbAVkzct2Rf6/qm3acMRkeatFQcglxU6zCTqKXzhQcibe8oFQuNV4Iyznuf7fUXF5xu99haLtg/n/n9qhg5Vx6SPU19sAuxU1GUY4z+ygAwaxf9LDCtupGVzBa6cX7MPgqVgyC1qXUUnhGh79ZD8svyJ0zlSzshk19v/6qsIIbuwYZhyXshoUqsgOLPRTRNPbJejl+06GEBV3NywohoC2ES+be+qKvI4CdI8DUT67fzBSHEqX9hre4dM+QC25ERYbjIfLtfjcPVP3YhgFJj6zC66h5A1eRt+zbbWRv55JEeMSPqbdCUFBcy0mOMuQdnnjJqtMHQpAGwa3Bt/se4uNhb73NjmItuX04RuFFVoup7aW8bYFJh94aYRIDlu8zomgfTdJLAJ/q4Ef2/O74ALBl/4cgevjwNDoWmkpm+PT2563gAWTu+abFmeE9v3SRpSggIRU1IeosCJfEQ=