language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: nIWgi6PuuluXuH+51Uv5DpGNTvYqPt1fU4BzbGPGSalJP0fpwYKEjb6/+xvN9icEtx+gtGGgLNCj58R+TbW1+dX6KI2zrUeatztaWQO/KZaJLv7EpIv6oQ2KiM8RUxiOl4AQVUL3KVsb/3VGWDTX5rEb15+1QJwKz/FtekO60Q850RbnsZ+8sE+eRj4izuI0LdnUOrqsOqgtKsqNcNgAvUFG9O9Rf9Xs9MjW3OtgBXJCqyBLGgU4cKXRiylV7o6q/buz0j+uCAiunaeQSTmQXQp6cfCuTCtT4D82TgPv0YLlK4bq6066dz+ov7WPWO8/C2eSKn8HrnWFqoMSJ80/lafBHnszEJh+HOxGHhFqhYmnDl/+5uAXCBRgovh1wrKJ2OXVSpSWeQDCbR9eAukcaB6vXElNMfPz6+2YDz5aLybbJ4ncfZ/5416dxKQp9g0ijoa3+wGc7xlSGRbaO0HbN+d4REudP1pmem0U3auWer2aNwZ6mS2Ee1PF4RdUhkjRjGAWOeeDALqNO/muFTWpHjVlEzrbAovMh/h/kCrOb5b94aMI/N0g3x42A1Z2tFe6FCKgmXJH0tr66Uo/2PiSuwCgCQ3F3TjIPEU0GICuFANzbB6w/SImj7clsSshEAi6RZdS7gGU6ubPnDo2OkHYktQmsytdEGUWARh58h83L2k=