language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: wJBFxOq3neLSSwPr/BjJEoexjPhoBLIDfbktMcs1grM3O+PthIQtBt71jgvO2XS2LGCa98dpcyClRswr8P1leQoJP0e7zK9dcdzA53fDyw9DyAozhhAJOzEE/qSB0pDuGLWYdeHZ905eC6uQ1C58TQjgy2FiCXvPoWpeutO507IND3kroGTgCqewXqmJgaHUpji5zPfJfi+1M9Hs/LxgSpRv23R+oWgpifAWIfwMMLbxi2/HKv83Nd1mR+Ygy3OhO1+KsIdzXBqq1W9h35G6Y6LfDETkVTWefMIxSNW5elmwLXBBoKt7ZaQDWEbUvhKNcjHkbdGLm8ejHNOl90/k5F5ofqYAWlkLG+xufkfuuuAhBIMGss/aum2DgvV2rtK8WJGwHz8p+/3kmDTDNtCJSUMZ8eE2xQyNO5vSWuNk+LUoMDIEXPZFT5d5bTdnQeEv46cz4Oc/tFDCFe6IbDWUK7rF2QanA+euxxh7FwHEbA+vFN6YzlEXhNygDBxi7wQTUnfHkfaXsg4i1Qun2B4Y+IAKnPFQwvOokMvsvQLovq9rye5s2W5YBlYHuydhMJkkpv0PZwrlosHg+jjaQJZQ3vFNUEAeDHEveITqiFgPClbO75cv8+cd3UdiELyTDib4+9G7h13eCjvf67u4HPSSfKeufOAZ0wncMNsApY7Hq3U=
